version: '3'

services:
  backend:
    build: ./
    container_name: music_magazine_container
    working_dir: /music_magazine
    restart: always
    command: 
      - ./commands/start_server.sh
    ports:
      - 8011:8010
    volumes:
      - ./src:/music_magazine/src
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data: { }
