version: '3'

services:
  backend:
    build: ./
    container_name: music_magazine_container
    working_dir: /music_magazine
    restart: always
    command:
      - ./commands/start_server.sh
    ports:
      - 8011:8010
    volumes:
      - ./src:/music_magazine/src
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 5000:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pg_data: {}
  pgadmin_data: {}
