# Generated by Django 3.2.13 on 2022-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magazine", "0002_alter_article_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="edit_date",
        ),
        migrations.RemoveField(
            model_name="article",
            name="publication_date",
        ),
        migrations.AddField(
            model_name="article",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="articletag",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="articletag",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="last_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
