# Generated by Django 3.2.13 on 2022-10-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20221013_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
