# Generated by Django 3.2.13 on 2022-10-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_auto_20221014_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='magazine.Tag'),
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
